export const ADD_TAXI_FARE = "ADD_TAXI_FARE";
// export const COMPLETE_TAXI_FARE = 'COMPLETE_TAXI_FARE';
// export const CLEAR_TAXI_FARE = 'CLEAR_TAXI_FARE';
// export const REMOVE_COMPLETED_TAXI_FARES = 'REMOVE_COMPLETED_TAXI_FARES';
export const UPDATE_TAXI_FARE = "UPDATE_TAXI_FARE";
export const REMOVE_TAXI_FARE = "REMOVE_TAXI_FARE";
